version: '3.8'

services:
  postgres:
    image: apache/age
    container_name: postgres-age
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
    network_mode: host
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  viewer:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host

volumes:
  postgres_data:
